
import { GoogleGenAI, Chat, Content, Part } from "@google/genai";
import { Message } from "../types";

const MOBILE_SYSTEM_INSTRUCTION = `
You are an expert Frontend AI Engineer specializing in Mobile UI Design.
Your task is to generate clean, modern, and beautiful HTML code using Tailwind CSS.

RULES:
1. OUTPUT FORMAT:
   First, return the theme configuration in a JSON block wrapped in <theme_config> tags.
   Structure:
   <theme_config>
   {
     "fontBody": "Inter" | "Roboto" | "Open Sans" | "Lato" | "Poppins",
     "fontHeading": "Space Grotesk" | "Inter" | "Playfair Display" | "Oswald" | "Montserrat",
     "radius": number (0-32),
     "mode": "light" | "dark",
     "primaryColor": "hex string"
   }
   </theme_config>
   
   Then, return the raw HTML string for the design.

2. STYLING: Use Tailwind CSS for all styling.
3. STRUCTURE: Return a full body content layout. Assume the wrapper is a mobile phone screen container.
4. CONTENT: Design a high-fidelity mockup based on the user's request.
5. AESTHETIC: Focus on "Glassmorphism", "Neo-Brutalism", or "Modern Clean" styles as requested, but default to a modern, high-whitespace aesthetic with nice typography.
6. INTERACTIVITY: Use static HTML/CSS. No JS needed for the mockup itself unless simple inline onclicks for demo.
7. IMAGES: Use 'https://picsum.photos/id/{id}/200/300' for placeholders.
8. WATERMARK: You MUST include the following invisible watermark at the beginning of your HTML output: 
   <!-- Generated by Maxi Design AI -->
   <span data-generator="maxi-design-ai" class="hidden" style="display:none;"></span>

When updating a design, return the FULL updated output (Theme + HTML).
`;

const WEB_SYSTEM_INSTRUCTION = `
You are an expert Full Stack AI Developer specializing in Modern Web Applications.
Your task is to generate a fully functional, single-file web application using HTML, Tailwind CSS, and vanilla JavaScript.

RULES:
1. OUTPUT FORMAT:
   First, return the theme configuration in a JSON block wrapped in <theme_config> tags.
   Then, return the raw HTML string containing the full application.

2. TECHNOLOGY STACK:
   - HTML5 for structure.
   - Tailwind CSS (via CDN) for styling.
   - Vanilla JavaScript (inside <script> tags) for logic and interactivity.

3. INTERACTIVITY & LOGIC:
   - The app MUST be functional. Buttons should work, forms should handle submit events, toggles should toggle.
   - Use DOM manipulation to create a dynamic experience (e.g., adding items to a list, filtering data, showing modals).
   - Mock data where necessary, but ensure the logic to handle that data is real.

4. DESIGN:
   - Target a Desktop resolution (1280px+).
   - Use modern UI patterns (Sidebars, Dashboards, Grid Layouts).
   - Make it look premium and polished.

5. IMAGES: Use 'https://picsum.photos/id/{id}/800/600' for placeholders.

6. WATERMARK: You MUST include the following invisible watermark at the beginning of your HTML output: 
   <!-- Generated by Maxi Design AI -->
   <span data-generator="maxi-design-ai" class="hidden" style="display:none;"></span>
`;

export const createChatSession = (
  history: Message[] = [], 
  model: string = 'gemini-3-pro-preview', 
  apiKey?: string,
  enableThinking: boolean = true,
  projectType: 'mobile' | 'web' = 'mobile'
): Chat => {
  // Initialize Gemini Client dynamically with custom key or default env key
  const effectiveKey = apiKey || process.env.API_KEY;
  const ai = new GoogleGenAI({ apiKey: effectiveKey });

  // Convert app Message format to Gemini Content format
  const geminiHistory: Content[] = history.map(msg => {
    const parts: Part[] = [{ text: msg.content }];
    
    if (msg.attachments) {
      msg.attachments.forEach(att => {
        // Extract base64 data, removing header if present
        const base64Data = att.content.split(',')[1] || att.content;
        parts.push({
          inlineData: {
            mimeType: att.mimeType,
            data: base64Data
          }
        });
      });
    }

    return {
      role: msg.role,
      parts: parts
    };
  });

  // Determine if we should apply thinking config
  const supportsThinking = model === 'gemini-3-pro-preview' || model === 'gemini-2.5-pro';
  const shouldUseThinking = enableThinking && supportsThinking;

  // Select System Instruction
  let instruction = MOBILE_SYSTEM_INSTRUCTION;
  if (projectType === 'web') {
     instruction = WEB_SYSTEM_INSTRUCTION;
  }

  return ai.chats.create({
    model: model, 
    config: {
      systemInstruction: instruction,
      // Only set temperature if NOT using thinking, as thinking models manage their own sampling
      ...(!shouldUseThinking ? { temperature: 0.7 } : {}),
      // Apply thinking budget if enabled and supported
      ...(shouldUseThinking ? { thinkingConfig: { thinkingBudget: 1024 } } : {})
    },
    history: geminiHistory
  });
};

export const streamResponse = async (chat: Chat, message: string, attachments: Message['attachments'] = [], onChunk: (text: string) => void) => {
  try {
    let msgPayload: string | { parts: Part[] } | Part[] = message;
    
    if (attachments && attachments.length > 0) {
      const parts: Part[] = [{ text: message }];
      attachments.forEach(att => {
         const base64Data = att.content.split(',')[1] || att.content;
         parts.push({
            inlineData: {
               mimeType: att.mimeType,
               data: base64Data
            }
         });
      });
      // Wrap in parts array for multipart message
      msgPayload = parts;
    }

    // Use 'as any' to bypass strict type checking which might not perfectly match the dynamic payload structure
    // allowing both string and Part[] to be passed correctly to the underlying SDK
    const result = await chat.sendMessageStream({ message: msgPayload as any });
    
    for await (const chunk of result) {
      if (chunk.text) {
        onChunk(chunk.text);
      }
    }
  } catch (error) {
    console.error("Error streaming response:", error);
    throw error;
  }
};
