
import { GoogleGenAI, Chat, Content, Part } from "@google/genai";
import { Message } from "../types";

const MOBILE_SYSTEM_INSTRUCTION = `
You are an expert Frontend AI Engineer specializing in Mobile UI Design.
Your task is to generate clean, modern, and beautiful HTML code using Tailwind CSS.

RULES:
1. OUTPUT FORMAT:
   First, return the theme configuration in a JSON block wrapped in <theme_config> tags.
   Structure:
   <theme_config>
   {
     "fontBody": "Inter" | "Roboto" | "Open Sans" | "Lato" | "Poppins",
     "fontHeading": "Space Grotesk" | "Inter" | "Playfair Display" | "Oswald" | "Montserrat",
     "radius": number (0-32),
     "mode": "light" | "dark",
     "primaryColor": "hex string"
   }
   </theme_config>
   
   Then, return the raw HTML string for the design.

2. STYLING: Use Tailwind CSS for all styling.
3. STRUCTURE: Return a full body content layout. Assume the wrapper is a mobile phone screen container.
4. CONTENT: Design a high-fidelity mockup based on the user's request.
5. AESTHETIC: Focus on "Glassmorphism", "Neo-Brutalism", or "Modern Clean" styles as requested, but default to a modern, high-whitespace aesthetic with nice typography.
6. INTERACTIVITY: Use static HTML/CSS. No JS needed for the mockup itself unless simple inline onclicks for demo.
7. IMAGES: Use 'https://picsum.photos/id/{id}/200/300' for placeholders.
8. WATERMARK: You MUST include the following invisible watermark at the beginning of your HTML output: 
   <!-- Generated by Maxi Design AI -->
   <span data-generator="maxi-design-ai" class="hidden" style="display:none;"></span>

When updating a design, return the FULL updated output (Theme + HTML).
`;

const PRESENTATION_SYSTEM_INSTRUCTION = `
You are an expert AI Presentation Designer specializing in creating beautiful, modern, scrollable slide decks using HTML and Tailwind CSS.

RULES:
1. OUTPUT FORMAT:
   First, return the theme configuration in a JSON block wrapped in <theme_config> tags (same structure as standard UI).
   Then, return the raw HTML string for the presentation.

2. STRUCTURE & LAYOUT:
   - The outer container MUST use classes: "h-screen w-full overflow-y-scroll snap-y snap-mandatory bg-white scroll-smooth".
   - Each slide MUST be a section with classes: "h-screen w-full snap-start flex flex-col items-center justify-center p-12 md:p-24 relative overflow-hidden".
   - Use standard 16:9 aspect ratio aesthetics.

3. CONTENT:
   - Create 3-5 distinct slides based on the user's prompt (e.g., Title Slide, Problem/Solution, Timeline, Team, Contact).
   - Use big, bold typography (text-6xl, text-8xl) for impact.
   - Use high-quality gradients and absolute positioned decorative elements.

4. AESTHETIC:
   - Modern, clean, and high-impact.
   - Use "Inter" or "Space Grotesk" for fonts.

5. IMAGES: Use 'https://picsum.photos/1920/1080' for backgrounds or slide images.
6. WATERMARK: You MUST include the following invisible watermark at the beginning of your HTML output: 
   <!-- Generated by Maxi Design AI -->
   <span data-generator="maxi-design-ai" class="hidden" style="display:none;"></span>
`;

export const createChatSession = (
  history: Message[] = [], 
  model: string = 'gemini-3-pro-preview', 
  apiKey?: string,
  enableThinking: boolean = true,
  projectType: 'mobile' | 'web' | 'presentation' = 'mobile'
): Chat => {
  // Initialize Gemini Client dynamically with custom key or default env key
  const effectiveKey = apiKey || process.env.API_KEY;
  const ai = new GoogleGenAI({ apiKey: effectiveKey });

  // Convert app Message format to Gemini Content format
  const geminiHistory: Content[] = history.map(msg => {
    const parts: Part[] = [{ text: msg.content }];
    
    if (msg.attachments) {
      msg.attachments.forEach(att => {
        // Extract base64 data, removing header if present
        const base64Data = att.content.split(',')[1] || att.content;
        parts.push({
          inlineData: {
            mimeType: att.mimeType,
            data: base64Data
          }
        });
      });
    }

    return {
      role: msg.role,
      parts: parts
    };
  });

  // Determine if we should apply thinking config
  const supportsThinking = model === 'gemini-3-pro-preview' || model === 'gemini-2.5-pro';
  const shouldUseThinking = enableThinking && supportsThinking;

  // Select System Instruction
  let instruction = MOBILE_SYSTEM_INSTRUCTION;
  if (projectType === 'presentation') {
     instruction = PRESENTATION_SYSTEM_INSTRUCTION;
  } else if (projectType === 'web') {
     instruction = MOBILE_SYSTEM_INSTRUCTION.replace('mobile phone screen container', 'desktop browser window (1280px width)');
  }

  return ai.chats.create({
    model: model, 
    config: {
      systemInstruction: instruction,
      // Only set temperature if NOT using thinking, as thinking models manage their own sampling
      ...(!shouldUseThinking ? { temperature: 0.7 } : {}),
      // Apply thinking budget if enabled and supported
      ...(shouldUseThinking ? { thinkingConfig: { thinkingBudget: 1024 } } : {})
    },
    history: geminiHistory
  });
};

export const streamResponse = async (chat: Chat, message: string, attachments: Message['attachments'] = [], onChunk: (text: string) => void) => {
  try {
    let msgPayload: string | { parts: Part[] } | Part[] = message;
    
    if (attachments && attachments.length > 0) {
      const parts: Part[] = [{ text: message }];
      attachments.forEach(att => {
         const base64Data = att.content.split(',')[1] || att.content;
         parts.push({
            inlineData: {
               mimeType: att.mimeType,
               data: base64Data
            }
         });
      });
      // Wrap in parts array for multipart message
      msgPayload = parts;
    }

    // Use 'as any' to bypass strict type checking which might not perfectly match the dynamic payload structure
    // allowing both string and Part[] to be passed correctly to the underlying SDK
    const result = await chat.sendMessageStream({ message: msgPayload as any });
    
    for await (const chunk of result) {
      if (chunk.text) {
        onChunk(chunk.text);
      }
    }
  } catch (error) {
    console.error("Error streaming response:", error);
    throw error;
  }
};
