import React from 'react';
import { ArrowLeft } from './Icons';

interface TermsOfServiceProps {
  onBack: () => void;
}

const TermsOfService: React.FC<TermsOfServiceProps> = ({ onBack }) => {
  return (
    <div className="min-h-screen bg-[#FDFBD4] p-6 md:p-12 font-sans text-black animate-in fade-in duration-500">
      <div className="max-w-3xl mx-auto">
        <button 
          onClick={onBack}
          className="mb-8 flex items-center gap-2 px-4 py-2 bg-white border-2 border-black rounded-full font-bold uppercase tracking-wider text-xs hover:bg-gray-100 shadow-[2px_2px_0px_0px_black] hover:translate-y-[1px] hover:translate-x-[1px] hover:shadow-[1px_1px_0px_0px_black] transition-all"
        >
          <ArrowLeft size={14} strokeWidth={3} /> Back
        </button>

        <div className="bg-white border-2 border-black rounded-3xl p-8 md:p-12 shadow-[8px_8px_0px_0px_black]">
          <h1 className="text-4xl md:text-5xl font-display font-black uppercase tracking-tighter mb-8 border-b-4 border-black pb-4">
            Terms of Service
          </h1>

          <div className="prose prose-lg prose-headings:font-black prose-headings:font-display prose-p:font-medium text-black max-w-none space-y-8">
            <section>
              <h3 className="text-2xl uppercase tracking-tight">1. Acceptance of Terms</h3>
              <p>
                By accessing and using Maxi Design ("the Application"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Application.
              </p>
            </section>

            <section>
              <h3 className="text-2xl uppercase tracking-tight">2. Use License</h3>
              <p>
                The Application is a tool for generating UI designs and code. You are granted a revocable, non-exclusive, non-transferable, limited license to use the Application for personal or commercial purposes, subject to these Terms.
              </p>
              <p>
                The code generated by the Application is yours to own and use without restriction. However, the Application itself, including its design and source code, remains our property.
              </p>
            </section>

            <section>
              <h3 className="text-2xl uppercase tracking-tight">3. AI Disclaimer</h3>
              <div className="bg-yellow-50 border-2 border-yellow-400 p-4 rounded-xl">
                <p className="m-0 text-sm">
                  <strong>Important:</strong> This Application uses Artificial Intelligence (AI) to generate code and designs. AI can make mistakes. The generated code is provided "as is" and may contain errors, bugs, or security vulnerabilities. You are responsible for reviewing and testing any code before using it in production.
                </p>
              </div>
            </section>

            <section>
              <h3 className="text-2xl uppercase tracking-tight">4. User Content</h3>
              <p>
                You are solely responsible for the inputs (prompts, images) you provide to the Application. You agree not to use the Application to generate content that is illegal, harmful, threatening, or violates the rights of others.
              </p>
            </section>

            <section>
              <h3 className="text-2xl uppercase tracking-tight">5. Limitation of Liability</h3>
              <p>
                In no event shall Maxi Design be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the Application.
              </p>
            </section>

            <section>
              <h3 className="text-2xl uppercase tracking-tight">6. API Usage</h3>
              <p>
                Access to the Application requires a connection to Google's Gemini API. You may be required to provide your own API key. You are responsible for any charges incurred from Google for your usage of their API.
              </p>
            </section>

            <div className="pt-8 mt-8 border-t-2 border-gray-100 text-sm font-bold text-gray-500">
              Last Updated: October 2024
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;